export interface Property {
  id: number;
  title: string;
  location: string;
  price: string;
  image: string;

  type: string;

  featured: boolean;
  verified: boolean;

  beds: number;
  baths: number;
  parking: number;
  area: string;

  features: string[];

  agent: string;
}

export const featuredProperties: Property[] = [
  {
    id: 1,
    title: "Modern 4-Bedroom Detached Duplex",
    location: "Oluyole Estate, Ibadan",
    price: "₦85,000,000",
    image: "/images/properties/property1.jpg",
    type: "For Sale",
    featured: true,
    verified: true,
    beds: 4,
    baths: 5,
    parking: 3,
    area: "650 sqm",
    features: ["POP Ceiling", "Fitted Kitchen", "CCTV", "Borehole", "Solar Power"],
    agent: "John Adeyemi",
  },
  {
    id: 2,
    title: "Luxury Smart Apartment",
    location: "Lekki Phase 1, Lagos",
    price: "₦120,000,000",
    image: "/images/properties/property2.jpg",
    type: "For Sale",
    featured: true,
    verified: true,
    beds: 5,
    baths: 6,
    parking: 4,
    area: "720 sqm",
    features: ["Swimming Pool", "Cinema", "Gym", "Smart Home", "CCTV"],
    agent: "Mary Johnson",
  },
  {
    id: 3,
    title: "Executive Short-let Apartment",
    location: "Victoria Island, Lagos",
    price: "₦250,000 / Night",
    image: "/images/properties/property3.jpg",
    type: "Short-let",
    featured: true,
    verified: true,
    beds: 2,
    baths: 2,
    parking: 2,
    area: "320 sqm",
    features: ["24/7 Power", "WiFi", "Swimming Pool", "Housekeeping", "Security"],
    agent: "David Williams",
  },
  {
    id: 4,
    title: "Contemporary Terrace Duplex",
    location: "Ajah, Lagos",
    price: "₦68,500,000",
    image: "/images/properties/property1.jpg",
    type: "For Sale",
    featured: false,
    verified: true,
    beds: 4,
    baths: 4,
    parking: 2,
    area: "510 sqm",
    features: ["Balcony", "Borehole", "Security", "Fitted Kitchen", "POP Ceiling"],
    agent: "Grace Adebayo",
  },
  {
    id: 5,
    title: "Serviced 3-Bedroom Apartment",
    location: "Wuse 2, Abuja",
    price: "₦7,500,000 / Year",
    image: "/images/properties/property2.jpg",
    type: "For Rent",
    featured: true,
    verified: true,
    beds: 3,
    baths: 3,
    parking: 2,
    area: "350 sqm",
    features: ["Elevator", "Gym", "24/7 Power", "Security", "Parking"],
    agent: "Samuel Peters",
  },
  {
    id: 6,
    title: "Prime Commercial Office",
    location: "Ikeja, Lagos",
    price: "₦250,000,000",
    image: "/images/properties/property3.jpg",
    type: "Commercial",
    featured: false,
    verified: true,
    beds: 0,
    baths: 4,
    parking: 20,
    area: "1500 sqm",
    features: ["Reception", "Parking", "Generator", "Elevator", "Security"],
    agent: "Ruth Okafor",
  },
  {
    id: 7,
    title: "Residential Land",
    location: "Moniya, Ibadan",
    price: "₦12,000,000",
    image: "/images/properties/property1.jpg",
    type: "Land",
    featured: false,
    verified: true,
    beds: 0,
    baths: 0,
    parking: 0,
    area: "600 sqm",
    features: ["Survey", "Deed", "Dry Land", "Accessible Road", "Verified"],
    agent: "Michael Bello",
  },
  {
    id: 8,
    title: "Luxury Penthouse",
    location: "Banana Island, Lagos",
    price: "₦650,000,000",
    image: "/images/properties/property2.jpg",
    type: "Luxury",
    featured: true,
    verified: true,
    beds: 5,
    baths: 6,
    parking: 4,
    area: "980 sqm",
    features: ["Private Lift", "Cinema", "Pool", "Gym", "Ocean View"],
    agent: "Jennifer Cole",
  },
  {
    id: 9,
    title: "Family Bungalow",
    location: "Akure, Ondo",
    price: "₦38,000,000",
    image: "/images/properties/property3.jpg",
    type: "For Sale",
    featured: false,
    verified: true,
    beds: 3,
    baths: 3,
    parking: 2,
    area: "420 sqm",
    features: ["Garden", "Fence", "POP Ceiling", "Borehole", "Security"],
    agent: "Ayo Akin",
  },
  {
    id: 10,
    title: "Executive Duplex",
    location: "Abeokuta, Ogun",
    price: "₦74,000,000",
    image: "/images/properties/property1.jpg",
    type: "For Sale",
    featured: true,
    verified: true,
    beds: 4,
    baths: 5,
    parking: 3,
    area: "600 sqm",
    features: ["Smart Home", "Solar", "CCTV", "Balcony", "Parking"],
    agent: "Tosin Adeoye",
  },
  {
    id: 11,
    title: "Waterfront Apartment",
    location: "Ikoyi, Lagos",
    price: "₦18,000,000 / Year",
    image: "/images/properties/property2.jpg",
    type: "For Rent",
    featured: true,
    verified: true,
    beds: 4,
    baths: 4,
    parking: 3,
    area: "540 sqm",
    features: ["Waterfront", "Gym", "Pool", "Security", "24/7 Power"],
    agent: "Chidinma Obi",
  },
  {
    id: 12,
    title: "Modern Studio Apartment",
    location: "Gwarinpa, Abuja",
    price: "₦3,200,000 / Year",
    image: "/images/properties/property3.jpg",
    type: "For Rent",
    featured: false,
    verified: true,
    beds: 1,
    baths: 1,
    parking: 1,
    area: "120 sqm",
    features: ["WiFi", "Security", "Parking", "Fitted Kitchen", "POP Ceiling"],
    agent: "Fatima Yusuf",
  },
];
