export const plans = [
  {
    name: "Basic",
    monthly: "Free",
    yearly: "Free",
    discount: "",
    monthlyListings: 5,
    yearlyListings: 60,
    monthlyRequests: 5,
    yearlyRequests: 60,
    monthlyInterior: 3,
    yearlyInterior: 36,
    popular: false,
    features: [
      "5 Property Listings Monthly",
      "5 Property Requests Monthly",
      "3 Interior Requests Monthly",
      "Standard Visibility",
      "Standard Support",
    ],
  },

  {
    name: "Silver",
    monthly: "₦5,000",
    yearly: "₦54,000",
    discount: "10% OFF",
    monthlyListings: 60,
    yearlyListings: 720,
    monthlyRequests: 60,
    yearlyRequests: 720,
    monthlyInterior: 20,
    yearlyInterior: 240,
    popular: false,
    features: [
      "60 Property Listings Monthly",
      "60 Property Requests Monthly",
      "20 Interior Requests Monthly",
      "Contact Visibility",
      "Priority Approval",
    ],
  },

  {
    name: "Gold",
    monthly: "₦12,000",
    yearly: "₦122,400",
    discount: "15% OFF",
    monthlyListings: 200,
    yearlyListings: 2400,
    monthlyRequests: 200,
    yearlyRequests: 2400,
    monthlyInterior: 60,
    yearlyInterior: 720,
    popular: true,
    features: [
      "200 Property Listings Monthly",
      "200 Property Requests Monthly",
      "60 Interior Requests Monthly",
      "Featured Listings",
      "High Search Ranking",
    ],
  },

  {
    name: "Platinum",
    monthly: "₦25,000",
    yearly: "₦240,000",
    discount: "20% OFF",
    monthlyListings: "Unlimited",
    yearlyListings: "Unlimited",
    monthlyRequests: "Unlimited",
    yearlyRequests: "Unlimited",
    monthlyInterior: "Unlimited",
    yearlyInterior: "Unlimited",
    popular: false,
    features: [
      "Unlimited Listings",
      "Unlimited Requests",
      "Unlimited Interior Projects",
      "Highest Visibility",
      "Premium Support",
    ],
  },
];
